name: watercraft
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.9.1
  - torchvision=0.24.1
  - torchaudio
  - pytorch-cuda=12.8
  - pip
  - pip:
    - ultralytics==8.3.239
    - easyocr==1.7.2
    - opencv-python==4.12.0.88
    - opencv-python-headless==4.12.0.88
    - pandas==2.3.3
    - numpy==2.2.6
    - pillow==11.3.0
    - matplotlib==3.10.8
    - scikit-image==0.25.2
    - scipy==1.16.3
    - tqdm==4.67.1
    - PyYAML==6.0.3
    - requests==2.32.5
    - pyclipper==1.4.0
    - shapely==2.1.2
    - python-bidi==0.6.7
    - polars==1.36.1
    - polars-runtime-32==1.36.1
    - psutil==7.1.3
    - filelock==3.19.1
    - fsspec==2025.9.0
    - ninja==1.13.0
    - ultralytics-thop==2.0.18
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - colorama==0.4.6
    - contourpy==1.3.3
    - cycler==0.12.1
    - fonttools==4.61.1
    - idna==3.11
    - ImageIO==2.37.2
    - Jinja2==3.1.6
    - kiwisolver==1.4.9
    - lazy_loader==0.4
    - MarkupSafe==2.1.5
    - mpmath==1.3.0
    - networkx==3.5
    - packaging==25.0
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - six==1.17.0
    - sympy==1.13.1
    - tifffile==2025.12.12
    - typing_extensions==4.15.0
    - tzdata==2025.3
    - urllib3==2.6.2

